[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# If you plan to deploy the backend separately, uncomment and modify
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-deployment-url.com/api/:splat"
#   status = 200
#   force = true
