[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/random-sentence"
  to = "/.netlify/functions/random-sentence"
  status = 200
  force = true

[[redirects]]
  from = "/api/translate"
  to = "/.netlify/functions/translate"
  status = 200
  force = true

# If you plan to deploy the backend separately, uncomment and modify
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-deployment-url.com/api/:splat"
#   status = 200
#   force = true
